version: 1.0.{build}
image: Visual Studio 2013
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - m.thakkars@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
